### ISSUE TITLE
Bug in callback causes crash

### ISSUE THREAD

**Issue by tcdev42** [hosackm/wavplayer#1]
There is a bug in the callback that overwrites the output buffer and causes a crash on the current version of PortAudio.

The problem is that num_read is returning the number of samples, not the number of frames, so your subsequent loops should be using num_read/2.

I simply added 'numread /= 2;' after the sf_read_float() and that appears to work.

**Comment by hosackm** [comment]
Thanks @msmcdoug.  I'll take a look into it.  I didn't take much care dealing with buffer sizes when I wrote this

**Comment by hosackm** [comment]
The sndfile info is sent into the portaudio callback everytime and this info is used in the call to `sf_read_float`.  That function fills the portaudio output buffer directly now.
