### ISSUE TITLE
How to loop a wav file?

### ISSUE THREAD

**Issue by IHNEL** [hosackm/wavplayer#5]
The wav file can be played with sample codein [wavplay.c](https://github.com/hosackm/wavplayer/blob/master/src/wavplay.c). but is there any way to make it loop infinitely until there is a breaking event?

**Comment by mhk-ableton** [comment]
As it's written, the stream will close at the end of the file but this doesn't have to happen. When the end of file is reached you could use `sf_seek(p_data->file, 0, SF_SEEK_SET)` to rewind back to the beginning of the file.

For creating a breaking event, you could add a member `done int;` to `callback_data_s` and initialize it to 0. Then when you'd like the break to occur you could set it to `1`. Then inside the callback you just check whether `p_data->done == 1` and exit.

**Comment by IHNEL** [comment]
Thanks @mhk-ableton 
I tried the above and it works perfectly.
